# **LAB SESSION 11**

**A22126551030**

**CSD-A[2/4]**

**DATA FRAMES** :

creating a data frame from a dictionary

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
mydata={'population':[20000,30000,15000,50000],'area':[200,300,150,500],'income':[20,30,15,50]}
df=pd.DataFrame(mydata)
print(df)

   population  area  income
0       20000   200      20
1       30000   300      30
2       15000   150      15
3       50000   500      50


using head method:

In [ ]:
print(df.head(2))

   population  area  income
0       20000   200      20
1       30000   300      30


arranging columns in aspecific order

In [ ]:
pd.DataFrame(mydata,columns=['area','income','population'])

area  income  population
0   200      20       20000
1   300      30       30000
2   150      15       15000
3   500      50       50000

adding indexes

In [ ]:
df2=pd.DataFrame(mydata,index=['pune','vizag','goa','hyd'])
print(df2)

       population  area  income
pune        20000   200      20
vizag       30000   300      30
goa         15000   150      15
hyd         50000   500      50


retrieving columns:it can be retrieved as a series

In [ ]:
df2['population']

pune     20000
vizag    30000
goa      15000
hyd      50000
Name: population, dtype: int64

In [ ]:
df2.area

pune     200
vizag    300
goa      150
hyd      500
Name: area, dtype: int64

retrieveing rows using 'loc'&'iloc'

In [ ]:
df2.loc['vizag']

population    30000
area            300
income           30
Name: vizag, dtype: int64

In [ ]:
df2.iloc[2]

population    15000
area            150
income           15
Name: goa, dtype: int64

assigning columns:

In [ ]:
df2['literacy']=[87,98,67,99]
print(df2)

       population  area  income  literacy
pune        20000   200      20        87
vizag       30000   300      30        98
goa         15000   150      15        67
hyd         50000   500      50        99


In [ ]:
df2['col']=np.arange(4)
print(df2)

       population  area  income  literacy  col
pune        20000   200      20        87    0
vizag       30000   300      30        98    1
goa         15000   150      15        67    2
hyd         50000   500      50        99    3


assigning a series to data frame

In [ ]:
ser1=pd.Series([2,3,5],index=['pune','vizag','hyd'])
df2['col']=ser1
print(df2)

       population  area  income  literacy  col
pune        20000   200      20        87  2.0
vizag       30000   300      30        98  3.0
goa         15000   150      15        67  NaN
hyd         50000   500      50        99  5.0


In [ ]:
ser2=pd.Series([34,56,89],index=['vizag','pune','goa'])
df2['literacy']=ser2
print(df2)

       population  area  income  literacy  col
pune        20000   200      20      56.0  2.0
vizag       30000   300      30      34.0  3.0
goa         15000   150      15      89.0  NaN
hyd         50000   500      50       NaN  5.0


creating a boolean column:

In [ ]:
df2['eligible']=df2.income>20
print(df2)

       population  area  income  literacy  col  eligible
pune        20000   200      20      56.0  2.0     False
vizag       30000   300      30      34.0  3.0      True
goa         15000   150      15      89.0  NaN     False
hyd         50000   500      50       NaN  5.0      True


In [ ]:
df2['eligible']=df2.population>=20000
print(df2)

       population  area  income  literacy  col  eligible
pune        20000   200      20      56.0  2.0      True
vizag       30000   300      30      34.0  3.0      True
goa         15000   150      15      89.0  NaN     False
hyd         50000   500      50       NaN  5.0      True


deleting a column using 'del' keword:

In [ ]:
del df2['eligible']
print(df2)

       population  area  income  literacy  col
pune        20000   200      20      56.0  2.0
vizag       30000   300      30      34.0  3.0
goa         15000   150      15      89.0  NaN
hyd         50000   500      50       NaN  5.0


retrieving name of columns present in the df2

In [ ]:
df2.columns

Index(['population', 'area', 'income', 'literacy', 'col', 'eligible'], dtype='object')

creating a data frame with nested dict of dicts:

In [ ]:
mydata2={'vizag':{'pop':30,'area':3,'income':300},'pune':{'pop':10,'area':1,'income':100},'goa':{'pop':40,'area':4,'income':400},'hyd':{'pop':20,'area':2,'income':200}}
df3=pd.DataFrame(mydata2)
print(df3)

        vizag  pune  goa  hyd
pop        30    10   40   20
area        3     1    4    2
income    300   100  400  200


transposing rows and columns:

In [ ]:
df4=df3.T
print(df4)

       pop  area  income
vizag   30     3     300
pune    10     1     100
goa     40     4     400
hyd     20     2     200


dict of series

In [ ]:
mydata3={'pop':df4['pop'][1:3],'area':df4['area'][:-2]}
pd.DataFrame(mydata3)

pop  area
goa    40.0   NaN
pune   10.0   1.0
vizag   NaN   3.0

naming to index and columns

In [ ]:
df4.index.name='cities'
df4.columns.name='details'
print(df4)

details  pop  area  income
cities                    
vizag     30     3     300
pune      10     1     100
goa       40     4     400
hyd       20     2     200


getting all values of data frame as an array

In [ ]:
print("values of df",df.values)
print("values of df2",df2.values)
print("values of df3",df3.values)
print("values of df4",df4.values)

values of df [[20000   200    20]
 [30000   300    30]
 [15000   150    15]
 [50000   500    50]]
values of df2 [[20000 200 20 56.0 2.0 True]
 [30000 300 30 34.0 3.0 True]
 [15000 150 15 89.0 nan False]
 [50000 500 50 nan 5.0 True]]
values of df3 [[ 30  10  40  20]
 [  3   1   4   2]
 [300 100 400 200]]
values of df4 [[ 30   3 300]
 [ 10   1 100]
 [ 40   4 400]
 [ 20   2 200]]
